# Generated by Django 4.1.7 on 2023-05-07 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaCovid19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100, verbose_name='Busqueda enfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busqueda', models.CharField(max_length=50, verbose_name='Busqueda medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_esp', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id especialidad')),
                ('nombre_esp', models.CharField(max_length=30, verbose_name='Nombre de la especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_med', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id medico')),
                ('rut_med', models.CharField(max_length=12, unique=True, verbose_name='Rut médico')),
                ('nombre_completo', models.CharField(max_length=50, verbose_name='Nombre médico')),
            ],
        ),
        migrations.CreateModel(
            name='ModificarPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres de usuario')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos de usuario')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo de usuario')),
                ('direccion', models.CharField(max_length=60, verbose_name='Dirección de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id_prev', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id previsión')),
                ('nombre_prev', models.CharField(max_length=40, verbose_name='Nombre previsión')),
            ],
        ),
        migrations.CreateModel(
            name='RecuperarContraseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=50)),
                ('contraseña_nueva', models.CharField(max_length=30)),
                ('confirmar_contraseña', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroUsuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id usuario')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres del usuario')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos del usuario')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo de usuario')),
                ('nombre_usuario', models.CharField(max_length=25, verbose_name='Nombre de usuario')),
                ('contraseña', models.CharField(max_length=30, verbose_name='Contraseña de usuario')),
                ('repetir_contraseña', models.CharField(max_length=30, verbose_name='Campo repetir contraseña')),
                ('direccion', models.CharField(max_length=60, verbose_name='Dirección de usuario')),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='Fecha de nacimiento de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_tipo_usuario', models.CharField(max_length=20, verbose_name='Nombre tipo usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ReservarHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, verbose_name='Rut de paciente')),
                ('prevision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prevision', verbose_name='Id previsión')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id_reclamo', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id reclamo')),
                ('nombres_rec', models.CharField(max_length=50, verbose_name='Nombres usuario')),
                ('apellidos_rec', models.CharField(max_length=50, verbose_name='Apellidos usuario')),
                ('rut_rec', models.CharField(max_length=12, verbose_name='Rut usuario')),
                ('celular', models.CharField(max_length=9, verbose_name='Nro celular usuario')),
                ('direccion_rec', models.CharField(max_length=60, verbose_name='Direccion usuario')),
                ('comentarios', models.TextField(max_length=150, verbose_name='Comentarios')),
                ('id_tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmarReserva',
            fields=[
                ('id_res', models.AutoField(primary_key=True, serialize=False, verbose_name='Id reserva')),
                ('rut', models.CharField(max_length=12, verbose_name='Rut paciente')),
                ('prevision', models.CharField(max_length=40, verbose_name='Id prevision de salud')),
                ('nombre_medico', models.CharField(max_length=30, verbose_name='Nombre médico')),
                ('dia_agendado', models.DateField()),
                ('hora_agendada', models.TimeField()),
                ('id_esp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.especialidad', verbose_name='Especialidad médico')),
            ],
        ),
    ]
